# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: counter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'counter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcounter.proto\x12\x07\x63ounter\"0\n\rUpdateRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"6\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bnew_balance\x18\x02 \x01(\x05\"$\n\x11GetBalanceRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\"%\n\x12GetBalanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\x32\x99\x01\n\x0e\x43ounterService\x12@\n\rUpdateBalance\x12\x16.counter.UpdateRequest\x1a\x17.counter.UpdateResponse\x12\x45\n\nGetBalance\x12\x1a.counter.GetBalanceRequest\x1a\x1b.counter.GetBalanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'counter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEREQUEST']._serialized_start=26
  _globals['_UPDATEREQUEST']._serialized_end=74
  _globals['_UPDATERESPONSE']._serialized_start=76
  _globals['_UPDATERESPONSE']._serialized_end=130
  _globals['_GETBALANCEREQUEST']._serialized_start=132
  _globals['_GETBALANCEREQUEST']._serialized_end=168
  _globals['_GETBALANCERESPONSE']._serialized_start=170
  _globals['_GETBALANCERESPONSE']._serialized_end=207
  _globals['_COUNTERSERVICE']._serialized_start=210
  _globals['_COUNTERSERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
