# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x07logging\"\x1d\n\nLogRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x0c\n\nGetRequest\"\x1f\n\x0bGetResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\x83\x01\n\x0eLoggingService\x12\x37\n\nLogMessage\x12\x13.logging.LogRequest\x1a\x14.logging.LogResponse\x12\x38\n\x0bGetMessages\x12\x13.logging.GetRequest\x1a\x14.logging.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=26
  _globals['_LOGREQUEST']._serialized_end=55
  _globals['_LOGRESPONSE']._serialized_start=57
  _globals['_LOGRESPONSE']._serialized_end=87
  _globals['_GETREQUEST']._serialized_start=89
  _globals['_GETREQUEST']._serialized_end=101
  _globals['_GETRESPONSE']._serialized_start=103
  _globals['_GETRESPONSE']._serialized_end=134
  _globals['_LOGGINGSERVICE']._serialized_start=137
  _globals['_LOGGINGSERVICE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
